kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: busy
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "3600"
      lifecycle:
        preStop:
          exec:
            command:
              - "sleep"
              - "15"
#      command:
#        - sleep
#        - "3600"