apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: termonitor
  labels:
    app: termonitor
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
